# Generated by Django 5.0.2 on 2024-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(default='default.png', upload_to='warehouse_pictures')),
            ],
        ),
    ]
